[package]
type = 'bash'
name = 'bash-std'
slug = 'std'
version = '0.0.0'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = 'Standard Bash functions'

[run]
dependencies = []
binDirs = []
sourceDirs = []
builtinDirs = []
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]
errexit = 'on'
pipefail = 'on'

[run.shoptOptions]
nullglob = 'on'
shift_verbose = 'on'
